name: midi_rooms
services:
  midi_rooms_postgres:
    image: postgres:17.7-alpine
    container_name: midi_rooms_postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - midi_rooms_network
    expose:
      - 5432
    volumes:
      - midi_rooms_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 10
  midi_rooms:
    image: ghcr.io/dimamik/midi_rooms
    container_name: midi_rooms
    restart: always
    networks:
      - nginx_network
      - midi_rooms_network
    expose:
      - 4000
    depends_on:
      midi_rooms_postgres:
        condition: service_healthy
    env_file:
      - ${PWD}/.env
    labels:
      - "com.centurylinklabs.watchtower.scope=midi_rooms"
  midi_rooms_watchtower:
    image: containrrr/watchtower
    container_name: midi_rooms_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 60 --cleanup midi_rooms --scope midi_rooms
    depends_on:
      - midi_rooms
    restart: unless-stopped
volumes:
  midi_rooms_db:
    driver: local

networks:
  nginx_network:
    name: nginx_network
    external: true
  midi_rooms_network:
    name: midi_rooms_network
    driver: bridge
    internal: true
